[package]
name = "oxy-fs"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
oxy-domain = { path = "../oxy-domain" }
parking_lot.workspace = true
thiserror.workspace = true
trash.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Storage_FileSystem",
  "Win32_UI_Shell",
  "Win32_System_Com",
] }

[dev-dependencies]
tempfile.workspace = true
