[package]
name = "oxy-fs"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
oxy-domain = { path = "../oxy-domain" }
parking_lot.workspace = true
thiserror.workspace = true
trash.workspace = true

[dev-dependencies]
tempfile.workspace = true

