[package]
name = "oxyviewer"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "oxyviewer_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
oxy-domain = { path = "../../../crates/oxy-domain" }
oxy-fs = { path = "../../../crates/oxy-fs" }
oxy-library = { path = "../../../crates/oxy-library" }
oxy-media = { path = "../../../crates/oxy-media" }
oxy-metadata = { path = "../../../crates/oxy-metadata" }
oxy-runtime = { path = "../../../crates/oxy-runtime" }
serde.workspace = true
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-log = "2"
