[package]
name = "oxy-media"
build = "build.rs"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
image.workspace = true
lcms2.workspace = true
libheif-rs.workspace = true
oxy-domain = { path = "../oxy-domain" }
tempfile.workspace = true
thiserror.workspace = true

[build-dependencies]
cc = { version = "1.2", features = ["parallel"] }
