[package]
name = "oxy-metadata"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
oxy-domain = { path = "../oxy-domain" }
oxy-fs = { path = "../oxy-fs" }
oxy-metadata-parser = { path = "../oxy-metadata-parser" }
libheif-rs.workspace = true
serde_json.workspace = true
sha2 = "0.10"
tempfile.workspace = true
thiserror.workspace = true
