//! Reference-parity tests.
//!
//! `oxy-faces` reimplements OpenCV's YuNet postprocessing, landmark alignment,
//! and SFace preprocessing. These tests compare the Rust implementation against
//! goldens generated by OpenCV itself (`tests/data/generate_reference.py`), so
//! the two implementations cannot silently drift apart.
//!
//! The tests need the pinned models in `target/native/face-models`
//! (`pnpm faces:prepare`). They skip with a message when the models are absent,
//! matching the repository's fixture convention, so a media-only checkout still
//! runs the suite.

use std::path::{Path, PathBuf};

use oxy_domain::{FaceAnalyzerSettings, PixelSize};
use oxy_faces::{FaceAnalyzer, FaceModelPaths, RgbImage, SFaceEmbedder, align_face, similarity};
use serde::Deserialize;

/// Detection settings matching the golden generator: OpenCV applies no minimum
/// face size, and `sanitized()` floors `min_face_pixels` at 8.
fn default_settings() -> FaceAnalyzerSettings {
    FaceAnalyzerSettings {
        detection_confidence: 0.9,
        nms_threshold: 0.3,
        max_faces_per_asset: 5000,
        min_face_pixels: 8,
        ..FaceAnalyzerSettings::default()
    }
}

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn data_dir() -> PathBuf {
    manifest_dir().join("tests").join("data")
}

/// Resolves the pinned model directory, or `None` when it has not been prepared.
fn model_paths() -> Option<FaceModelPaths> {
    let directory = std::env::var_os("OXY_FACE_MODEL_DIR").map_or_else(
        || manifest_dir().join("../../target/native/face-models"),
        PathBuf::from,
    );
    let detector = directory.join("face_detection_yunet_2023mar.onnx");
    let embedder = directory.join("face_recognition_sface_2021dec.onnx");
    if detector.is_file() && embedder.is_file() {
        Some(FaceModelPaths::new(detector, embedder, 640))
    } else {
        eprintln!(
            "skipping: face models are not prepared; run `pnpm faces:prepare` \
             or set OXY_FACE_MODEL_DIR"
        );
        None
    }
}

fn analyzer(settings: FaceAnalyzerSettings) -> Option<FaceAnalyzer> {
    let paths = model_paths()?;
    Some(FaceAnalyzer::load(&paths, settings).expect("the pinned models load"))
}

#[test]
fn full_image_policy_invalidates_previous_detection_checkpoints() {
    let Some(analyzer) = analyzer(default_settings()) else {
        return;
    };
    assert!(
        analyzer.detector_fingerprint().contains("/full-v1/"),
        "old preview-based checkpoints must be analyzed again"
    );
}

/// Deterministic pattern; `generate_reference.py::synthetic_rgb` mirrors this.
fn synthetic_rgb(width: u32, height: u32) -> RgbImage {
    let mut data = Vec::with_capacity(width as usize * height as usize * 3);
    for y in 0..height as i64 {
        for x in 0..width as i64 {
            data.push(((x * 3 + y * 5) % 256) as u8);
            data.push(((x * 7 + y * 11) % 256) as u8);
            data.push(((x * 13 + y * 17) % 256) as u8);
        }
    }
    RgbImage::new(width, height, data).expect("synthetic buffer matches its size")
}

fn load_image(path: &Path) -> RgbImage {
    let image = image::open(path)
        .unwrap_or_else(|error| panic!("failed to decode {}: {error}", path.display()))
        .to_rgb8();
    RgbImage::new(image.width(), image.height(), image.into_raw()).expect("decoded buffer is RGB8")
}

fn read_golden<T: for<'de> Deserialize<'de>>(name: &str) -> T {
    let path = data_dir().join("golden").join(name);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|error| panic!("failed to parse {}: {error}", path.display()))
}

fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

fn bounding_box_iou(left: [f32; 4], right: [f32; 4]) -> f32 {
    let x1 = left[0].max(right[0]);
    let y1 = left[1].max(right[1]);
    let x2 = (left[0] + left[2]).min(right[0] + right[2]);
    let y2 = (left[1] + left[3]).min(right[1] + right[3]);
    let intersection = (x2 - x1).max(0.0) * (y2 - y1).max(0.0);
    let union = left[2] * left[3] + right[2] * right[3] - intersection;
    if union <= 0.0 {
        0.0
    } else {
        intersection / union
    }
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct SfaceGolden {
    embedding: Vec<f32>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct YunetGolden {
    face_count: usize,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct AlignGolden {
    landmarks: Vec<[f32; 2]>,
    aligned_sum: i64,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct PortraitGolden {
    fixture_sha256: String,
    source_width: u32,
    source_height: u32,
    detections: Vec<PortraitDetection>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct PortraitDetection {
    #[serde(rename = "box")]
    bounding_box: [f32; 4],
    landmarks: Vec<[f32; 2]>,
    score: f32,
    embedding: Vec<f32>,
}

/// Repeats `source` in a `columns` x `rows` grid, producing a group-photo-sized
/// image whose individual faces are much smaller than the detector input.
fn tile_image(source: &RgbImage, columns: u32, rows: u32) -> RgbImage {
    let width = source.width() * columns;
    let height = source.height() * rows;
    let mut data = vec![0u8; width as usize * height as usize * 3];
    for row in 0..rows {
        for column in 0..columns {
            for y in 0..source.height() as usize {
                let target_x = column * source.width();
                let target_y = row * source.height() + y as u32;
                let target = ((target_y as usize) * width as usize + target_x as usize) * 3;
                let source_row = y * source.width() as usize * 3;
                let bytes = source.width() as usize * 3;
                data[target..target + bytes]
                    .copy_from_slice(&source.data()[source_row..source_row + bytes]);
            }
        }
    }
    RgbImage::new(width, height, data).expect("composite buffer matches its size")
}

/// Reduces an image so its long edge is `edge`, standing in for the
/// delivery-bounded raster preview level.
fn resize_to_long_edge(source: &RgbImage, edge: u32) -> RgbImage {
    let long = source.width().max(source.height());
    let scale = edge as f32 / long as f32;
    let width = ((source.width() as f32 * scale).round() as u32).max(1);
    let height = ((source.height() as f32 * scale).round() as u32).max(1);
    let image = image::RgbImage::from_raw(source.width(), source.height(), source.data().to_vec())
        .expect("buffer matches its dimensions");
    let resized =
        image::imageops::resize(&image, width, height, image::imageops::FilterType::Triangle);
    RgbImage::new(width, height, resized.into_raw()).expect("resized buffer is RGB8")
}

fn settings_with_tiling(tiled: bool) -> FaceAnalyzerSettings {
    FaceAnalyzerSettings {
        detection_confidence: 0.9,
        nms_threshold: 0.3,
        max_faces_per_asset: 5000,
        min_face_pixels: 8,
        detect_small_faces: tiled,
        ..FaceAnalyzerSettings::default()
    }
}

#[test]
fn tiling_recovers_small_faces_a_single_pass_misses() {
    let Some(paths) = model_paths() else {
        return;
    };
    let tile = load_image(&data_dir().join("fixtures").join("two_people.jpg"));
    // 4x4 copies: 32 faces of ~100 px inside a 3200 px frame. One 640 input
    // downscales each to ~20 px; a tile keeps them at ~35 px. Measured on this
    // fixture, the single pass finds 24 of 32 and the tiled pass finds all 32.
    let composite = tile_image(&tile, 4, 4);
    assert_eq!((composite.width(), composite.height()), (3200, 1880));

    let analyze = |tiled: bool| {
        FaceAnalyzer::load(&paths, settings_with_tiling(tiled))
            .expect("the pinned models load")
            .analyze("asset", Path::new("/tmp/composite.jpg"), "rev", &composite)
            .expect("analysis succeeds")
    };
    let untiled = analyze(false);
    let tiled = analyze(true);

    assert!(
        tiled.len() > untiled.len(),
        "tiling must recover faces the single pass misses ({} vs {})",
        tiled.len(),
        untiled.len()
    );
    assert_eq!(
        tiled.len(),
        32,
        "every face in the composite must be found once"
    );
    // Every detection is a distinct face: no tile should produce a duplicate
    // that survived the merge.
    for (index, face) in tiled.iter().enumerate() {
        for other in tiled.iter().skip(index + 1) {
            assert!(
                face.observation.bbox.iou(other.observation.bbox) < 0.3,
                "merged detections must not overlap: {:?} vs {:?}",
                face.observation.bbox,
                other.observation.bbox
            );
        }
    }
}

#[test]
fn full_resolution_analysis_keeps_faces_the_bounded_preview_loses() {
    let Some(paths) = model_paths() else {
        return;
    };
    let tile = load_image(&data_dir().join("fixtures").join("two_people.jpg"));
    // 4x4 copies: 32 faces, each ~100 px wide inside a 3200 px frame.
    let composite = tile_image(&tile, 4, 4);
    // The raster preview render level is bounded to 512 px on the long edge.
    let bounded = resize_to_long_edge(&composite, 512);
    assert_eq!(bounded.width(), 512);

    let count = |image: &RgbImage| {
        FaceAnalyzer::load(&paths, settings_with_tiling(true))
            .expect("the pinned models load")
            .analyze("asset", Path::new("/tmp/composite.jpg"), "rev", image)
            .expect("analysis succeeds")
            .len()
    };
    let bounded_faces = count(&bounded);
    let full_faces = count(&composite);

    assert_eq!(
        full_faces, 32,
        "full-resolution analysis must find every face"
    );
    // Measured on this fixture: the 512 px preview finds 24 of 32, the full
    // frame finds all 32. The lost eight are the ones a group photo is made of,
    // which is exactly what the analysis render level exists to prevent.
    assert_eq!(
        bounded_faces, 24,
        "the bounded preview must lose eight faces; if this changes, the \
         delivery bound or the detector moved and the analysis level needs a \
         fresh measurement"
    );
}

#[test]
fn sface_embedding_matches_opencv_reference() {
    let Some(paths) = model_paths() else {
        return;
    };
    let golden: SfaceGolden = read_golden("sface_synthetic.json");
    let input = synthetic_rgb(112, 112);

    let embedder = SFaceEmbedder::load(&paths.embedder).expect("embedder loads");
    let embedding = embedder.embed(&input).expect("inference succeeds");

    assert_eq!(embedding.len(), golden.embedding.len());
    let score = similarity(&embedding, &golden.embedding);
    assert!(
        score > 0.999,
        "SFace embedding diverged from OpenCV: cosine {score}"
    );
}

#[test]
fn yunet_finds_no_faces_in_a_noise_pattern() {
    let Some(analyzer) = analyzer(default_settings()) else {
        return;
    };
    let golden: YunetGolden = read_golden("yunet_synthetic.json");
    assert_eq!(golden.face_count, 0);
    let input = synthetic_rgb(640, 640);
    let faces = analyzer
        .analyze("asset", Path::new("/tmp/noise.png"), "rev", &input)
        .expect("inference succeeds");
    assert!(
        faces.is_empty(),
        "a deterministic noise pattern must not produce detections, found {}",
        faces.len()
    );
}

#[test]
fn alignment_matches_opencv_warp_affine() {
    let golden: AlignGolden = read_golden("align_synthetic.json");
    let canvas = synthetic_rgb(320, 320);
    let aligned = align_face(&canvas, &golden.landmarks, 112).expect("alignment succeeds");
    let reference = load_image(
        &data_dir()
            .join("golden")
            .join("align_synthetic_aligned.png"),
    );

    assert_eq!(aligned.width(), reference.width());
    assert_eq!(aligned.height(), reference.height());

    let mut total = 0i64;
    let mut difference = 0i64;
    for (left, right) in aligned.data().iter().zip(reference.data().iter()) {
        total += i64::from(*left);
        difference += (i64::from(*left) - i64::from(*right)).abs();
    }
    // OpenCV interpolates 8-bit affine warps in fixed point, so both the total
    // brightness and individual samples differ by a few least-significant bits.
    // The tolerances below catch a structural mismatch (wrong transform, wrong
    // coordinate convention, wrong border handling) without pinning rounding.
    let brightness_error = (total - golden.aligned_sum).abs() as f64;
    let brightness_budget = (golden.aligned_sum.abs() as f64 * 1e-4).max(512.0);
    assert!(
        brightness_error <= brightness_budget,
        "aligned brightness diverged: {total} vs {}",
        golden.aligned_sum
    );
    let mean = difference as f64 / aligned.data().len() as f64;
    assert!(mean < 3.0, "mean per-channel warp error {mean} is too high");
}

#[test]
fn full_pipeline_matches_opencv_on_a_portrait() {
    let Some(analyzer) = analyzer(default_settings()) else {
        return;
    };
    let golden: PortraitGolden = read_golden("portrait_reference.json");
    let fixture = data_dir().join("fixtures").join("two_people.jpg");
    let bytes = std::fs::read(&fixture).expect("fixture is committed");
    assert_eq!(
        sha256_hex(&bytes),
        golden.fixture_sha256,
        "the committed fixture changed; regenerate the goldens"
    );

    let input = load_image(&fixture);
    assert_eq!(input.width(), golden.source_width);
    assert_eq!(input.height(), golden.source_height);

    let analyzed = analyzer
        .analyze("asset", &fixture, "rev", &input)
        .expect("analysis succeeds");
    assert_eq!(
        analyzed.len(),
        golden.detections.len(),
        "detection count diverged from OpenCV"
    );

    let size = PixelSize {
        width: input.width(),
        height: input.height(),
    };
    for reference in &golden.detections {
        let expected = reference.bounding_box;
        // Pair by geometry rather than by index: a near-tie in score could
        // reorder two detections without meaning anything.
        let (face, overlap) = analyzed
            .iter()
            .map(|face| {
                let (x, y, width, height) = face.observation.bbox.to_pixels(size);
                (face, bounding_box_iou([x, y, width, height], expected))
            })
            .max_by(|left, right| left.1.partial_cmp(&right.1).unwrap())
            .expect("at least one detection");
        assert!(
            overlap > 0.5,
            "no Rust detection overlaps the OpenCV box {expected:?} (best IoU {overlap})"
        );

        // Scores use a loose tolerance because the two JPEG decoders differ by
        // a few least-significant bits.
        assert!(
            (face.observation.detection_score - reference.score).abs() < 0.02,
            "score {} vs {}",
            face.observation.detection_score,
            reference.score
        );

        let (x, y, width, height) = face.observation.bbox.to_pixels(size);
        for (actual, wanted, label) in [
            (x, expected[0], "x"),
            (y, expected[1], "y"),
            (width, expected[2], "width"),
            (height, expected[3], "height"),
        ] {
            assert!(
                (actual - wanted).abs() < 6.0,
                "{label}: {actual} vs {wanted}"
            );
        }

        for (point, wanted) in face
            .observation
            .landmarks
            .iter()
            .zip(reference.landmarks.iter())
        {
            let px = point.x * size.width as f32;
            let py = point.y * size.height as f32;
            assert!(
                (px - wanted[0]).abs() < 6.0 && (py - wanted[1]).abs() < 6.0,
                "landmark ({px}, {py}) vs ({}, {})",
                wanted[0],
                wanted[1]
            );
        }

        let score = similarity(&face.embedding, &reference.embedding);
        assert!(
            score > 0.99,
            "embedding diverged from OpenCV: cosine {score}"
        );
    }
}

#[test]
fn analysis_is_idempotent_and_revision_sensitive() {
    // Two identical analyses must agree, and a different revision must change
    // the observation id: the Host relies on this to reject stale writes.
    let Some(analyzer) = analyzer(default_settings()) else {
        return;
    };
    let input = load_image(&data_dir().join("fixtures").join("two_people.jpg"));
    let first = analyzer
        .analyze("asset", Path::new("/tmp/a.jpg"), "rev-1", &input)
        .expect("analysis succeeds");
    let second = analyzer
        .analyze("asset", Path::new("/tmp/a.jpg"), "rev-1", &input)
        .expect("analysis succeeds");
    let third = analyzer
        .analyze("asset", Path::new("/tmp/a.jpg"), "rev-2", &input)
        .expect("analysis succeeds");

    assert!(!first.is_empty());
    assert_eq!(first.len(), second.len());
    for (left, right) in first.iter().zip(second.iter()) {
        assert_eq!(
            left.observation.observation_id,
            right.observation.observation_id
        );
        assert_eq!(left.observation.bbox, right.observation.bbox);
        assert_eq!(left.embedding, right.embedding);
    }
    assert_ne!(
        first[0].observation.observation_id,
        third[0].observation.observation_id
    );
}

#[test]
fn min_face_pixels_filters_small_detections() {
    let Some(paths) = model_paths() else {
        return;
    };
    let input = load_image(&data_dir().join("fixtures").join("two_people.jpg"));
    let analyze = |min_face_pixels: u32| {
        FaceAnalyzer::load(
            &paths,
            FaceAnalyzerSettings {
                min_face_pixels,
                ..default_settings()
            },
        )
        .expect("the pinned models load")
        .analyze("asset", Path::new("/tmp/a.jpg"), "rev", &input)
        .expect("analysis succeeds")
    };
    let permissive = analyze(8);
    let strict = analyze(512);
    assert!(!permissive.is_empty());
    assert!(
        strict.is_empty(),
        "min_face_pixels must drop every detection on a downscaled fixture"
    );
}
